#!/bin/bash

set -e

DATABASE_NAME=$2

if [ -z "$DATABASE_NAME" ]; then
  DATABASE_NAME="censinet-dev"
fi

read -p "Are you sure you want to drop and restore the database? (y/N): " confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
  echo "Aborted."
  exit 1
fi

echo "Downloading latest dump from S3..."
aws s3 cp s3://censinet-default-shared-db-dump/common/202509041120.dump db/latest.dump --profile lower-envs

dropdb --if-exists $DATABASE_NAME -U postgres
createdb $DATABASE_NAME -U postgres

echo "Restoring database..."
pg_restore \
  -U postgres \
  --dbname=$DATABASE_NAME \
  --jobs=4 \
  --disable-triggers \
  --no-owner \
  --no-privileges \
  --no-tablespaces \
  --verbose \
  db/latest.dump

echo "Database restored successfully."
rm db/latest.dump
