version: 1

# Master list of all backup steps
:steps:
  - :name: brew
    :label: "Brewfile"

  - :name: apt
    :label: "APT Packages"

  - :name: snap
    :label: "Snap Packages"

  - :name: sensitive
    :label: "SSH Keys, GPG Keys, AWS Keys, Personal Creds"
    :contents:
      - .ssh
      - .gnupg
      - .aws
      - .config/private

  - :name: scripts
    :contents:
      - .local/bin/*

  - :name: dotfiles
    :contents:
      - .bashrc
      - .bash_profile
      - .fdignore
      - .gitconfig
      - .gitconfig_local
      - .gitattributes
      - .hushlogin
      - .profile
      - .viminfo
      - .vimrc
      - .zlogin
      - .zprofile
      - .zsh
      - .zshrc
      - .zshenv

  - :name: configdirs
    :contents:
      - .antigravity
      - .bun
      - .claude
      - .codeium
      - .config
      - .cursor
      - .docker
      - .gemini
      - .local
      - .mkshrc
      - .netrc
      - .oh-my-zsh
      - .opencode
      - .promptuary
      - .ruby-lsp
      - .supermaven
      - .vscode
      - .warp
      - .windsurf

  - :name: fonts
    :label: "Fonts"
    :contents:
      - Library/Fonts

  - :name: histories
    :label: "Shell Histories"
    :contents:
      - "*history"

  - :name: homedirs
    :label: "Home Directories"
    :contents:
      - Applications
      - code
      - Desktop
      - Documents
      - Downloads
      - go
      - Motionik-Recordings
      - Movies
      - Music
      - Pictures
      - Public
      - Themes

  - :name: app_config
    :label: "Application Support and Preferences"
    :contents:
      - "Library/Application Support"
      - Library/Preferences

  - :name: backup
    :label: Everything else
    :contents: ~/
# Git backup configuration - which steps to save to git
:git:
  :dest: ./
  :steps:
    - brew
    - apt
    - snap
    - scripts
    - dotfiles

# Vault backup configuration - which steps to save to vault
:vault:
  :dest: ~/VaultBackup
  :steps:
    - sensitive
    - scripts
    - dotfiles
    - configdirs
    - fonts
    - histories
    - homedirs
    - app_config
    - backup
  :restore_skip:
    - backup

:defaults:
  :relative_root: ~/
  # Excludes are ignored if added to 'contents' for a given vault block
  :exclude_patterns:
    - "*.log"
    - "*.pid"
    - .DS_Store
    - VaultBackup
    - .GlobalPreferences
    - .Trash
    - .android
    - .bundle
    - .cache
    - .cargo
    - .cups
    - .dapr
    - .eye
    - .gem
    - .gk
    - .god
    - .hex
    - .hyper_plugins
    - .lesshst
    - .matplotlib
    - .mix
    - .mono
    - .node_modules
    - .npm
    - .CFUserTextEncoding
    - .nvm
    - .ollama
    - .pgadmin
    - .pnpm-state
    - .rustup
    - .terraform.d
    - .wget-hsts
    - .yarn
    - .zcompdump*
    - .zsh_sessions
    - ByHost
    - Cache*
    - CrashReporter
    - GPUCache
    - Google/Chrome/GrShaderCache
    - Google/Chrome/Safe Browsing
    - MobileMeAccounts.plist
    - ShaderCache
    - Thumbs.db
    - com.apple.*
    - docker.sock
    - com.docker.docker
    - networkservices.plist
    - node_modules
    - tmp*
    - vendor
